import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  header: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  backButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  backText: { color: colors.brand, fontSize: 24, fontWeight: "700" },
  headerCopy: { flex: 1 },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  title: { color: colors.brandDeep, fontSize: 24, fontWeight: "900" },
  subtitle: { color: colors.textMuted, fontSize: 13, marginTop: 2 },
  content: { gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.xxl },
  guardCard: {
    backgroundColor: colors.coral,
    borderRadius: radii.lg,
    gap: spacing.xs,
    padding: spacing.lg,
  },
  guardTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900" },
  guardText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
  tabs: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: "row",
    padding: spacing.xxs,
  },
  tab: { alignItems: "center", borderRadius: radii.pill, flex: 1, paddingVertical: spacing.sm },
  tabActive: { backgroundColor: colors.brand },
  tabText: { color: colors.textMuted, fontSize: 14, fontWeight: "800" },
  tabTextActive: { color: colors.surface },
  stateCard: { alignItems: "center", gap: spacing.sm, padding: spacing.xl },
  stateText: { color: colors.textMuted, fontSize: 14, textAlign: "center" },
  errorCard: {
    alignItems: "center",
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  errorText: { color: colors.brandDeep, fontSize: 13, lineHeight: 18, textAlign: "center" },
  retryButton: { backgroundColor: colors.brand, borderRadius: radii.pill, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  retryText: { color: colors.surface, fontWeight: "800" },
  metricRow: { flexDirection: "row", gap: spacing.sm },
  metricCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flex: 1, padding: spacing.md },
  metricValue: { color: colors.brand, fontSize: 28, fontWeight: "900" },
  metricLabel: { color: colors.textMuted, fontSize: 12, lineHeight: 16 },
  formCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.lg },
  sectionTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900" },
  fieldLabel: { color: colors.brandDeep, fontSize: 13, fontWeight: "800", marginTop: spacing.xs },
  chipRow: { flexDirection: "row", gap: spacing.xs, paddingVertical: spacing.xxs },
  chip: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: 10 },
  chipActive: { backgroundColor: colors.energy, borderColor: colors.energy },
  chipText: { color: colors.textMuted, fontSize: 13, fontWeight: "700" },
  chipTextActive: { color: colors.brandDeep },
  input: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: typeScale.body, minHeight: 48, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  textareaSmall: { minHeight: 76, textAlignVertical: "top" },
  textarea: { minHeight: 110, textAlignVertical: "top" },
  primaryButton: { alignItems: "center", backgroundColor: colors.brand, borderRadius: radii.pill, justifyContent: "center", minHeight: 50, paddingHorizontal: spacing.lg },
  primaryButtonText: { color: colors.surface, fontSize: 15, fontWeight: "900" },
  buttonDisabled: { opacity: 0.45 },
  successText: { color: colors.success, fontSize: 13, fontWeight: "700", textAlign: "center" },
  listSection: { gap: spacing.sm },
  emptyText: { color: colors.textMuted, fontSize: 14, paddingVertical: spacing.sm },
  itemCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing.xs, padding: spacing.md },
  itemTopRow: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" },
  itemTitle: { color: colors.brandDeep, flex: 1, fontSize: 15, fontWeight: "900" },
  itemMeta: { color: colors.focus, fontSize: 12, fontWeight: "800" },
  itemText: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  statusPill: { backgroundColor: colors.coral, borderRadius: radii.pill, color: colors.brandDeep, fontSize: 11, fontWeight: "800", overflow: "hidden", paddingHorizontal: spacing.sm, paddingVertical: spacing.xxs },
  checkRow: { alignItems: "center", flexDirection: "row", gap: spacing.sm, paddingVertical: spacing.xs },
  checkbox: { alignItems: "center", borderColor: colors.border, borderRadius: radii.sm, borderWidth: 2, height: 24, justifyContent: "center", width: 24 },
  checkboxActive: { backgroundColor: colors.brand, borderColor: colors.brand },
  checkmark: { color: colors.surface, fontSize: 14, fontWeight: "900" },
  checkText: { color: colors.text, fontSize: 14, fontWeight: "700" },
  actionRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs, marginTop: spacing.xs },
  secondaryButton: { borderColor: colors.brand, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  secondaryButtonText: { color: colors.brand, fontSize: 12, fontWeight: "800" },
});
