import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  activityCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  activityDescription: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  activityMeta: {
    color: colors.textMuted,
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
  },
  activityMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  activityStatus: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  activityStatusText: {
    fontSize: 12,
    fontWeight: "800",
  },
  activityTitle: {
    color: colors.brandDeep,
    flex: 1,
    fontSize: 17,
    fontWeight: "800",
  },
  activityTitleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.sm,
  },
  activityXp: {
    color: colors.focus,
    fontSize: 14,
    fontWeight: "900",
  },
  activityOpenText: {
    color: colors.brand,
    fontSize: typeScale.caption,
    fontWeight: "800",
    marginTop: spacing.sm,
  },
  backButton: {
    alignSelf: "flex-start",
    paddingVertical: spacing.xs,
  },
  backText: {
    color: colors.brand,
    fontSize: 15,
    fontWeight: "800",
  },
  content: {
    gap: spacing.xl,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  emptyCard: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    padding: spacing.lg,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  eventCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  eventDate: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: spacing.xxs,
  },
  eventInfo: {
    flex: 1,
  },
  eventLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  eventXp: {
    color: colors.success,
    fontSize: 14,
    fontWeight: "900",
  },
  headerDescription: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.xs,
  },
  headerEyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  headerTitle: {
    color: colors.brandDeep,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -1,
    marginTop: spacing.xxs,
  },
  hero: {
    backgroundColor: colors.brandDeep,
    borderRadius: radii.lg,
    overflow: "hidden",
    padding: spacing.lg,
  },
  heroAccent: {
    backgroundColor: colors.energy,
    borderRadius: radii.pill,
    height: 92,
    opacity: 0.22,
    position: "absolute",
    right: -24,
    top: -24,
    width: 92,
  },
  heroCaption: {
    color: "#E8DCEB",
    fontSize: 13,
    marginTop: spacing.sm,
  },
  heroLevel: {
    alignSelf: "flex-start",
    backgroundColor: colors.energy,
    borderRadius: radii.pill,
    color: colors.brandDeep,
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  heroProgress: {
    backgroundColor: "#60466A",
    borderRadius: radii.pill,
    height: 12,
    marginTop: spacing.lg,
    overflow: "hidden",
  },
  heroProgressFill: {
    backgroundColor: colors.energy,
    borderRadius: radii.pill,
    height: "100%",
  },
  heroProgressRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing.xs,
  },
  heroProgressText: {
    color: "#F7EEF8",
    fontSize: 12,
    fontWeight: "700",
  },
  heroTotal: {
    color: colors.surface,
    fontSize: 42,
    fontWeight: "900",
    letterSpacing: -1.5,
    marginTop: spacing.md,
  },
  list: {
    gap: spacing.sm,
  },
  metricCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flex: 1,
    minWidth: 92,
    padding: spacing.md,
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: spacing.xxs,
  },
  metricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metricValue: {
    color: colors.brandDeep,
    fontSize: 24,
    fontWeight: "900",
  },
  rankingCurrent: {
    backgroundColor: colors.coral,
    borderColor: colors.energy,
  },
  rankingEntry: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.md,
  },
  rankingLevel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: spacing.xxs,
  },
  rankingName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  rankingNameWrap: {
    flex: 1,
  },
  rankingPosition: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.pill,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  rankingPositionText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: "900",
  },
  rankingXp: {
    color: colors.focus,
    fontSize: 14,
    fontWeight: "900",
  },
  retryButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.pill,
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  retryText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: "800",
  },
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  sectionDescription: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xxs,
  },
  sectionHeader: {
    marginBottom: spacing.md,
  },
  sectionTitle: {
    color: colors.brandDeep,
    fontSize: 22,
    fontWeight: "900",
  },
  sourceCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing.md,
  },
  sourceLabel: {
    color: colors.text,
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  sourceValue: {
    color: colors.focus,
    fontSize: 14,
    fontWeight: "900",
  },
  statusCard: {
    alignItems: "flex-start",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  statusText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
});
