import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  content: { gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.xxl },
  topBar: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  backButton: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  backText: { color: colors.brandDeep, fontWeight: "800" },
  eyebrow: {
    color: colors.brand,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.4,
  },
  title: { color: colors.text, fontSize: 30, fontWeight: "900" },
  subtitle: { color: colors.textMuted, fontSize: typeScale.body, lineHeight: 22 },
  sectionTitle: { color: colors.text, fontSize: typeScale.lead, fontWeight: "900", marginTop: spacing.sm },
  sectionHint: { color: colors.textMuted, fontSize: typeScale.caption, lineHeight: 18 },
  searchRow: { flexDirection: "row", gap: spacing.sm },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: typeScale.body,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  inputMultiline: { minHeight: 100, textAlignVertical: "top" },
  searchButton: {
    alignItems: "center",
    backgroundColor: colors.brandDeep,
    borderRadius: radii.md,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  searchButtonText: { color: colors.surface, fontWeight: "900" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  chip: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  chipSelected: { backgroundColor: colors.brandDeep, borderColor: colors.brandDeep },
  chipText: { color: colors.textMuted, fontSize: typeScale.caption, fontWeight: "800" },
  chipTextSelected: { color: colors.surface },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  summaryCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: "46%",
    padding: spacing.md,
  },
  summaryValue: { color: colors.brandDeep, fontSize: 24, fontWeight: "900" },
  summaryLabel: { color: colors.textMuted, fontSize: typeScale.caption, fontWeight: "700" },
  stateCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.xl,
  },
  stateText: { color: colors.textMuted, textAlign: "center" },
  errorText: { color: colors.coral, fontWeight: "800", textAlign: "center" },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  cardPressed: { opacity: 0.75 },
  cardTop: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" },
  cardCopy: { flex: 1, gap: spacing.xxs },
  cardTitle: { color: colors.text, fontSize: typeScale.lead, fontWeight: "900" },
  cardMeta: { color: colors.textMuted, fontSize: typeScale.caption, lineHeight: 18 },
  cardText: { color: colors.text, fontSize: typeScale.body, lineHeight: 21 },
  badge: { borderRadius: radii.pill, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  badgePublished: { backgroundColor: colors.energy },
  badgeDraft: { backgroundColor: colors.focus },
  badgeArchived: { backgroundColor: colors.border },
  badgeText: { color: colors.brandDeep, fontSize: typeScale.caption, fontWeight: "900" },
  rankingRow: { alignItems: "center", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" },
  rankingPosition: { color: colors.brand, fontSize: typeScale.lead, fontWeight: "900", width: 38 },
  rankingName: { color: colors.text, flex: 1, fontWeight: "800" },
  rankingXp: { color: colors.brandDeep, fontWeight: "900" },
  pager: { flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flex: 1,
    padding: spacing.md,
  },
  secondaryButtonText: { color: colors.brandDeep, fontWeight: "900" },
  buttonDisabled: { opacity: 0.45 },
  label: { color: colors.text, fontSize: typeScale.caption, fontWeight: "900", letterSpacing: 0.5 },
  fieldGroup: { gap: spacing.xs },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.brandDeep,
    borderRadius: radii.md,
    padding: spacing.md,
  },
  primaryButtonText: { color: colors.surface, fontWeight: "900" },
  dangerButton: {
    alignItems: "center",
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    flex: 1,
    padding: spacing.md,
  },
  dangerButtonText: { color: colors.surface, fontWeight: "900" },
  success: {
    backgroundColor: colors.energy,
    borderRadius: radii.md,
    color: colors.brandDeep,
    fontWeight: "800",
    padding: spacing.md,
  },
  warning: { color: colors.coral, fontWeight: "800" },
  divider: { backgroundColor: colors.border, height: 1, marginVertical: spacing.xs },
  answers: { gap: spacing.xs },
  answer: { backgroundColor: colors.background, borderRadius: radii.md, gap: spacing.xs, padding: spacing.sm },
  answerQuestion: { color: colors.textMuted, fontSize: typeScale.caption, fontWeight: "800" },
  answerValue: { color: colors.text, lineHeight: 20 },
  actionRow: { flexDirection: "row", gap: spacing.sm },
});
