import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  content: {
    alignSelf: "center",
    maxWidth: 720,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
  },
  back: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderRadius: radii.sm,
    minHeight: 44,
    paddingRight: spacing.sm,
    justifyContent: "center",
  },
  backText: {
    color: colors.brand,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  loading: {
    marginTop: spacing.xxl,
  },
  error: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  errorTitle: {
    color: colors.text,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  errorText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  retry: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.sm,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  retryText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: "900",
  },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.xl,
  },
  titleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    justifyContent: "space-between",
    marginTop: spacing.xs,
  },
  title: {
    color: colors.brandDeep,
    flexShrink: 1,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 42,
  },
  status: {
    backgroundColor: colors.coral,
    borderRadius: radii.pill,
    color: colors.brandDeep,
    fontSize: 11,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  metadata: {
    color: colors.brand,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 21,
    marginTop: spacing.sm,
  },
  audience: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 21,
    marginTop: spacing.xs,
  },
  editButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.sm,
    justifyContent: "center",
    marginTop: spacing.md,
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  editButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: "900",
  },
  description: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 25,
    marginTop: spacing.lg,
  },
  linkError: {
    color: colors.focus,
    fontSize: 14,
    fontWeight: "800",
    marginTop: spacing.md,
  },
  pressed: {
    opacity: 0.7,
  },
});
