import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  content: {
    alignSelf: "center",
    maxWidth: 720,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
  },
  back: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderRadius: radii.sm,
    justifyContent: "center",
    minHeight: 44,
    paddingRight: spacing.sm,
  },
  backText: {
    color: colors.brand,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.lg,
  },
  title: {
    color: colors.brandDeep,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 42,
    marginTop: spacing.xs,
  },
  description: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  loading: {
    marginTop: spacing.xxl,
  },
  errorCard: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  errorTitle: {
    color: colors.text,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  errorText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  section: {
    marginTop: spacing.xl,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: colors.text,
    flexShrink: 1,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  sectionDescription: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xs,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderWidth: 1,
    color: colors.text,
    fontSize: typeScale.body,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  multiline: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  helper: {
    color: colors.textMuted,
    fontSize: typeScale.caption,
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  choices: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  choice: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  choiceSelected: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  choiceText: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "900",
  },
  choiceTextSelected: {
    color: colors.surface,
  },
  studentName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  studentDetail: {
    color: colors.textMuted,
    fontSize: typeScale.caption,
    marginTop: spacing.xxs,
  },
  addButton: {
    alignItems: "center",
    borderColor: colors.brand,
    borderRadius: radii.sm,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  addButtonText: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "900",
  },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  cardTitle: {
    color: colors.brandDeep,
    flexShrink: 1,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  removeButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.sm,
  },
  removeText: {
    color: colors.focus,
    fontSize: 13,
    fontWeight: "900",
  },
  submit: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.md,
    justifyContent: "center",
    marginTop: spacing.xl,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
  },
  submitDisabled: {
    opacity: 0.5,
  },
  submitText: {
    color: colors.surface,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  retry: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.sm,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  retryText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: "900",
  },
  pressed: {
    opacity: 0.7,
  },
});
