import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  content: {
    alignSelf: "center",
    maxWidth: 720,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
  },
  back: {
    alignSelf: "flex-start",
    borderRadius: radii.sm,
    justifyContent: "center",
    minHeight: 44,
    paddingVertical: spacing.xs,
  },
  backText: {
    color: colors.brand,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.xl,
  },
  title: {
    color: colors.brandDeep,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 42,
    marginTop: spacing.xs,
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  stateCard: {
    alignItems: "flex-start",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  stateText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  errorTitle: {
    color: colors.focus,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  emptyTitle: {
    color: colors.brandDeep,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  maintenanceCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    marginTop: spacing.xl,
    overflow: "hidden",
    padding: spacing.lg,
  },
  statusPill: {
    alignSelf: "flex-start",
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  statusPillText: {
    color: colors.focus,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  maintenanceTitle: {
    color: colors.brandDeep,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -0.8,
    marginTop: spacing.lg,
  },
  maintenanceText: {
    color: colors.text,
    fontSize: typeScale.body,
    fontWeight: "700",
    lineHeight: 25,
    marginTop: spacing.sm,
  },
  automaticText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: spacing.lg,
  },
  sessionCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    marginTop: spacing.lg,
    padding: spacing.lg,
  },
  sessionStatus: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  sessionStatusLive: {
    backgroundColor: colors.success,
  },
  sessionStatusEnded: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderWidth: 1,
  },
  sessionStatusText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  sessionStatusTextLive: {
    color: colors.surface,
  },
  sessionStatusTextEnded: {
    color: colors.textMuted,
  },
  sessionTitle: {
    color: colors.brandDeep,
    fontSize: typeScale.lead,
    fontWeight: "900",
    marginTop: spacing.md,
  },
  sessionMeta: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xs,
  },
  sessionDate: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
    marginTop: spacing.md,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.md,
    justifyContent: "center",
    marginTop: spacing.lg,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  secondaryButton: {
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderWidth: 1,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  secondaryButtonText: {
    color: colors.brand,
    fontSize: 14,
    fontWeight: "900",
  },
  feedback: {
    color: colors.focus,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 22,
    marginTop: spacing.lg,
  },
  securityNote: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: spacing.xl,
    textAlign: "center",
  },
});
