import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  topBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  backText: { color: colors.brand, fontSize: 14, fontWeight: "900" },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.xl,
  },
  title: {
    color: colors.text,
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 39,
    marginTop: spacing.xs,
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  searchRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  searchInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: typeScale.body,
    minHeight: 52,
    paddingHorizontal: spacing.md,
  },
  searchButton: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.md,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: spacing.md,
  },
  searchButtonText: { color: colors.surface, fontWeight: "900" },
  filterLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
    marginTop: spacing.lg,
  },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  chip: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    minHeight: 40,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  chipSelected: { backgroundColor: colors.brand, borderColor: colors.brand },
  chipText: { color: colors.textMuted, fontSize: 13, fontWeight: "800" },
  chipTextSelected: { color: colors.surface },
  resultSummary: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
    marginTop: spacing.xl,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  cardPressed: { opacity: 0.72 },
  cardTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
  },
  cardCopy: { flex: 1 },
  cardName: { color: colors.text, fontSize: typeScale.lead, fontWeight: "900" },
  cardEmail: { color: colors.textMuted, fontSize: 14, marginTop: spacing.xxs },
  badge: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  badgeActive: { backgroundColor: "#E4F4EC" },
  badgeInactive: { backgroundColor: colors.coral },
  badgeText: { color: colors.text, fontSize: 11, fontWeight: "900" },
  cardMeta: {
    color: colors.focus,
    fontSize: 12,
    fontWeight: "900",
    marginTop: spacing.md,
  },
  warning: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginTop: spacing.xs,
  },
  stateCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    marginTop: spacing.xl,
    padding: spacing.xl,
  },
  stateTitle: { color: colors.text, fontSize: typeScale.lead, fontWeight: "900" },
  stateText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xs,
    textAlign: "center",
  },
  loadMore: {
    alignItems: "center",
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderWidth: 1,
    marginTop: spacing.lg,
    minHeight: 48,
    padding: spacing.md,
  },
  loadMoreText: { color: colors.brand, fontWeight: "900" },
  identityCard: {
    backgroundColor: colors.brandDeep,
    borderRadius: radii.lg,
    marginTop: spacing.lg,
    padding: spacing.lg,
  },
  identityName: { color: colors.surface, fontSize: 26, fontWeight: "900" },
  identityEmail: { color: "#E9DDEA", fontSize: 14, marginTop: spacing.xs },
  identityMeta: {
    color: colors.energy,
    fontSize: 12,
    fontWeight: "900",
    marginTop: spacing.md,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: typeScale.lead,
    fontWeight: "900",
    marginTop: spacing.xl,
  },
  infoCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  infoLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "800" },
  infoValue: { color: colors.text, fontSize: 15, fontWeight: "800", marginTop: spacing.xxs },
  infoDivider: { backgroundColor: colors.border, height: 1, marginVertical: spacing.md },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md },
  metric: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    minWidth: "46%",
    padding: spacing.md,
  },
  metricValue: { color: colors.text, fontSize: 24, fontWeight: "900" },
  metricLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "800", marginTop: spacing.xxs },
});
