import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  content: { alignSelf: "center", maxWidth: 760, padding: spacing.lg, paddingBottom: spacing.xxl, width: "100%" },
  backButton: { alignSelf: "flex-start", paddingVertical: spacing.xs },
  backText: { color: colors.brand, fontSize: typeScale.body, fontWeight: "900" },
  eyebrow: { color: colors.focus, fontSize: typeScale.caption, fontWeight: "900", letterSpacing: 1.2, marginTop: spacing.lg },
  title: { color: colors.brandDeep, fontSize: typeScale.title, fontWeight: "900", letterSpacing: -1.2, lineHeight: 42, marginTop: spacing.xs },
  subtitle: { color: colors.textMuted, fontSize: typeScale.body, lineHeight: 24, marginTop: spacing.sm },
  uploadCard: { backgroundColor: colors.coral, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.sm, marginTop: spacing.xl, padding: spacing.lg },
  sectionTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900", marginTop: spacing.xl },
  label: { color: colors.textMuted, fontSize: typeScale.caption, fontWeight: "900", letterSpacing: 1, marginTop: spacing.xs },
  input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: typeScale.body, minHeight: 50, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs, marginTop: spacing.sm },
  chip: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  chipSelected: { backgroundColor: colors.brand, borderColor: colors.brand },
  chipText: { color: colors.text, fontSize: 13, fontWeight: "800" },
  chipTextSelected: { color: colors.surface },
  primaryButton: { alignItems: "center", backgroundColor: colors.brand, borderRadius: radii.md, justifyContent: "center", marginTop: spacing.sm, minHeight: 52, paddingHorizontal: spacing.lg },
  primaryButtonText: { color: colors.surface, fontSize: typeScale.body, fontWeight: "900" },
  secondaryButton: { alignItems: "center", alignSelf: "flex-start", backgroundColor: colors.surface, borderColor: colors.brand, borderRadius: radii.md, borderWidth: 1, justifyContent: "center", marginTop: spacing.sm, minHeight: 46, paddingHorizontal: spacing.lg },
  secondaryButtonText: { color: colors.brand, fontSize: 14, fontWeight: "900" },
  selectedFile: { color: colors.text, fontSize: 14, fontWeight: "800" },
  disabled: { opacity: 0.55 },
  success: { color: colors.success, fontSize: 14, fontWeight: "800", lineHeight: 21 },
  error: { color: colors.focus, fontSize: 14, fontWeight: "800", lineHeight: 21 },
  searchRow: { alignItems: "center", flexDirection: "row", gap: spacing.sm, marginTop: spacing.md },
  searchInput: { flex: 1 },
  searchButton: { alignItems: "center", backgroundColor: colors.brand, borderRadius: radii.md, justifyContent: "center", minHeight: 50, paddingHorizontal: spacing.md },
  searchButtonText: { color: colors.surface, fontWeight: "900" },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.lg },
  metric: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexGrow: 1, minWidth: 100, padding: spacing.md },
  metricValue: { color: colors.brandDeep, fontSize: 24, fontWeight: "900" },
  metricLabel: { color: colors.textMuted, fontSize: 13, fontWeight: "800" },
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.xs, marginTop: spacing.sm, padding: spacing.lg },
  cardPressed: { opacity: 0.75 },
  cardTop: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" },
  cardCopy: { flex: 1 },
  cardTitle: { color: colors.brandDeep, fontSize: typeScale.body, fontWeight: "900" },
  cardFile: { color: colors.textMuted, fontSize: 13, marginTop: spacing.xxs },
  badge: { backgroundColor: colors.coral, borderRadius: radii.pill, color: colors.focus, fontSize: 11, fontWeight: "900", overflow: "hidden", paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  cardMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 20 },
  stateCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.sm, marginTop: spacing.lg, padding: spacing.xl },
  stateTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900", textAlign: "center" },
  stateText: { color: colors.textMuted, fontSize: 14, lineHeight: 21, textAlign: "center" },
});
