import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  content: {
    alignSelf: "center",
    maxWidth: 760,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
  },
  backButton: { alignSelf: "flex-start", paddingVertical: spacing.xs },
  backText: { color: colors.brand, fontSize: typeScale.body, fontWeight: "900" },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.lg,
  },
  title: {
    color: colors.brandDeep,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 42,
    marginTop: spacing.xs,
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  statusCardActive: { backgroundColor: colors.coral, borderColor: colors.energy },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.pill,
    color: colors.surface,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    overflow: "hidden",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  cardTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900" },
  cardText: { color: colors.textMuted, fontSize: 14, lineHeight: 21 },
  cardMeta: { color: colors.textMuted, fontSize: typeScale.caption, lineHeight: 18 },
  actionButton: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.md,
    justifyContent: "center",
    marginTop: spacing.xs,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
  },
  actionButtonActive: { backgroundColor: colors.surface, borderColor: colors.brand, borderWidth: 1 },
  actionButtonText: { color: colors.surface, fontSize: typeScale.body, fontWeight: "900" },
  actionButtonTextActive: { color: colors.brand },
  disabled: { opacity: 0.55 },
  summaryRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.lg },
  summaryCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 210,
    padding: spacing.lg,
  },
  summaryLabel: { color: colors.textMuted, fontSize: typeScale.caption, fontWeight: "900", letterSpacing: 0.7 },
  summaryValue: { color: colors.brandDeep, fontSize: 24, fontWeight: "900", marginTop: spacing.xs },
  notice: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    marginTop: spacing.lg,
    padding: spacing.lg,
  },
  noticeTitle: { color: colors.brandDeep, fontSize: typeScale.body, fontWeight: "900" },
  noticeText: { color: colors.textMuted, fontSize: 14, lineHeight: 21, marginTop: spacing.xs },
  success: { color: colors.success, fontSize: 14, fontWeight: "800", lineHeight: 21, marginTop: spacing.md },
  error: { color: colors.focus, fontSize: 14, fontWeight: "800", lineHeight: 21, marginTop: spacing.md },
  stateCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.xl,
  },
  stateTitle: { color: colors.brandDeep, fontSize: typeScale.lead, fontWeight: "900", textAlign: "center" },
  stateText: { color: colors.textMuted, fontSize: 14, lineHeight: 21, textAlign: "center" },
  retryButton: {
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderWidth: 1,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  retryText: { color: colors.brand, fontSize: 14, fontWeight: "900" },
});
