import { StyleSheet } from "react-native";

import { colors, radii, spacing, typeScale } from "@/theme/tokens";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: colors.background, flex: 1 },
  keyboard: { flex: 1 },
  content: {
    alignSelf: "center",
    maxWidth: 720,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
  },
  back: {
    alignItems: "center",
    alignSelf: "flex-start",
    justifyContent: "center",
    minHeight: 44,
    paddingRight: spacing.sm,
  },
  backText: { color: colors.brand, fontSize: typeScale.body, fontWeight: "900" },
  eyebrow: {
    color: colors.focus,
    fontSize: typeScale.caption,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: spacing.lg,
  },
  title: {
    color: colors.brandDeep,
    fontSize: typeScale.title,
    fontWeight: "900",
    letterSpacing: -1.2,
    lineHeight: 42,
    marginTop: spacing.xs,
  },
  description: {
    color: colors.textMuted,
    fontSize: typeScale.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  loading: { marginTop: spacing.xxl },
  section: { marginTop: spacing.xl },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: colors.text,
    flexShrink: 1,
    fontSize: typeScale.lead,
    fontWeight: "900",
  },
  sectionDescription: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xs,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderWidth: 1,
    color: colors.text,
    fontSize: typeScale.body,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  multiline: { minHeight: 104, textAlignVertical: "top" },
  helper: {
    color: colors.textMuted,
    fontSize: typeScale.caption,
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  choices: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  choice: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  choiceSelected: { backgroundColor: colors.brand, borderColor: colors.brand },
  choiceDisabled: { opacity: 0.45 },
  choiceText: { color: colors.brand, fontSize: 13, fontWeight: "900" },
  choiceTextSelected: { color: colors.surface },
  lessonChoice: {
    alignItems: "flex-start",
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  lessonSelected: { backgroundColor: colors.coral, borderColor: colors.brand },
  lessonTitle: { color: colors.text, fontSize: 14, fontWeight: "900" },
  lessonMeta: { color: colors.textMuted, fontSize: 12, marginTop: spacing.xxs },
  addButton: {
    alignItems: "center",
    borderColor: colors.brand,
    borderRadius: radii.sm,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  addButtonText: { color: colors.brand, fontSize: 13, fontWeight: "900" },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  cardTitle: {
    color: colors.brandDeep,
    flexShrink: 1,
    fontSize: typeScale.body,
    fontWeight: "900",
  },
  removeButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.sm,
  },
  removeText: { color: colors.focus, fontSize: 13, fontWeight: "900" },
  infoCard: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    gap: spacing.xs,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  infoTitle: { color: colors.text, fontSize: 14, fontWeight: "900" },
  infoText: { color: colors.textMuted, fontSize: 14, lineHeight: 21 },
  errorCard: {
    backgroundColor: colors.coral,
    borderRadius: radii.md,
    gap: spacing.sm,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  errorTitle: { color: colors.text, fontSize: typeScale.lead, fontWeight: "900" },
  errorText: { color: colors.textMuted, fontSize: 14, lineHeight: 21 },
  successCard: {
    backgroundColor: colors.surface,
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderWidth: 1,
    marginTop: spacing.lg,
    padding: spacing.md,
  },
  successText: { color: colors.brand, fontSize: 14, fontWeight: "900" },
  submit: {
    alignItems: "center",
    backgroundColor: colors.brand,
    borderRadius: radii.md,
    justifyContent: "center",
    marginTop: spacing.xl,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
  },
  submitDisabled: { opacity: 0.5 },
  submitText: { color: colors.surface, fontSize: typeScale.body, fontWeight: "900" },
  secondary: {
    alignItems: "center",
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: "center",
    marginTop: spacing.md,
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  secondaryText: { color: colors.brand, fontSize: 14, fontWeight: "900" },
  danger: {
    alignItems: "center",
    borderColor: colors.focus,
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: "center",
    marginTop: spacing.md,
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  dangerConfirm: { backgroundColor: colors.focus },
  dangerText: { color: colors.focus, fontSize: 14, fontWeight: "900" },
  dangerConfirmText: { color: colors.surface, fontSize: 14, fontWeight: "900" },
  buttonRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  retry: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.brand,
    borderRadius: radii.sm,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  retryText: { color: colors.surface, fontSize: 14, fontWeight: "900" },
  pressed: { opacity: 0.7 },
});
